Issue #48 - add 'rozo storage add'
* take hosts, interface and port as parameters
* check the current storage config file
* apply modification

Here is the original storage.conf:

~~~~
listen = (
    {
        addr = "*";
        port = 41001;
    } );
storages = (
    {
        cid = 1;
        sid = 2;
        root = "/srv/rozofs/storages/storage_1_2";
    },
    {
        cid = 1;
        sid = 3;
        root = "/srv/rozofs/storages/storage_1_3";
    },
    {
        cid = 1;
        sid = 1;
        root = "/srv/rozofs/storages/storage_1_1";
    },
    {
        cid = 1;
        sid = 4;
        root = "/srv/rozofs/storages/storage_1_4";
    } );
~~~~

~~~~
Exception: entry *:41001 already exists.
~~~~

Once * is removed:

~~~~

localhost:
- addr: 1.1.1.1
  port: 1234

localhost:
- addr: 1.1.1.1
  port: 1234
- addr: 1.1.1.2
  port: 1234

Exception: entry 1.1.1.2:1234 already exists.
~~~~

The following is the new storage.conf:

~~~~
listen = (
    {
        addr = "1.1.1.1";
        port = 1234;
    },
    {
        addr = "1.1.1.2";
        port = 1234;
    } );
storages = (
    {
        cid = 1;
        sid = 2;
        root = "/srv/rozofs/storages/storage_1_2";
    },
    {
        cid = 1;
        sid = 3;
        root = "/srv/rozofs/storages/storage_1_3";
    },
    {
        cid = 1;
        sid = 1;
        root = "/srv/rozofs/storages/storage_1_1";
    },
    {
        cid = 1;
        sid = 4;
        root = "/srv/rozofs/storages/storage_1_4";
    } );
~~~~