Fix undefined bug #?? on 'export update'
When trying to update an export with 'rozo export update' modifying the
password, the system asks the current password and the new one.
The case where no password was set was not handled.

~~~~
$ rozo export list -E localhost
eid 1:
  vid: 1
  root: /srv/rozofs/exports/export_1
  md5: ''
  squota: ''
  hquota: ''
eid 2:
  vid: 1
  root: /srv/rozofs/exports/export_2
  md5: ''
  squota: ''
  hquota: ''

$ rozo -d export update 2 -E localhost -p robertdeniro -s 2G
Traceback (most recent call last):
  File "./rozo", line 267, in main
    getattr(m, 'dispatch')(action_namespace)
  File "/home/dim/git/rozofs/build/manager/build/lib.linux-i686-2.7/rozofs/cli/export.py", line 93, in dispatch
    globals()[args.action.replace('-', '_')](p, args)
  File "/home/dim/git/rozofs/build/manager/build/lib.linux-i686-2.7/rozofs/cli/export.py", line 50, in update
    platform.update_export(args.eid[0], args.current, args.passwd, args.squota, args.hquota)
  File "/home/dim/git/rozofs/build/manager/build/lib.linux-i686-2.7/rozofs/core/platform.py", line 634, in update_export
    raise "Current password needed."
TypeError: exceptions must be old-style classes or derived from BaseException, not str
Traceback (most recent call last):
  File "./rozo", line 283, in <module>
    sys.exit(main())
  File "./rozo", line 276, in main
    raise(e)
TypeError: exceptions must be old-style classes or derived from BaseException, not str
~~~~

Now the system checks if a password is set before asking the current password.

~~~~
$ rozo -d export update 2 -E localhost -p robertdeniro -s 2G
$ rozo export list -E localhost
eid 1:
  vid: 1
  root: /srv/rozofs/exports/export_1
  md5: ''
  squota: ''
  hquota: ''
eid 2:
  vid: 1
  root: /srv/rozofs/exports/export_2
  md5: eqjhaB5aJTeH7A7ZPD7a0
  squota: 2G
  hquota: ''
~~~~